<?php

namespace phpXFace\core\ui\html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-09-16 at 21:36:08.
 */
class AnchorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Anchor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->object = new Anchor();
        $this->object->getAttributes()->addClass("Test123");
    }

    public function testDecorator() {
        $this->object->getAttributes()->addClass("Test123");
    }

}
