<?php
namespace phpXFace\core\ui\html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-09-13 at 22:25:40.
 */
class ContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Container
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Container;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testRenderWithoutAttributes(){
        $output = $this->object->render();
        $this->assertEquals( '<div></div>', $output );
    }
    
    public function testRenderWithAttributes(){
        $this->object->getAttributes()->addClass("test");
        $output = $this->object->render();        
        $this->assertEquals( '<div class="test"></div>', $output );
    }
    
    public function testNestedRenderWithoutAttributes(){
        $output = $this->object->render();        
        $this->assertEquals( '<div></div>', $output );
    }
    
    public function testNestedRenderWithAttributes(){  
        $this->object->getAttributes()->addClass("test1");
        $output = $this->object->render();        
        $this->assertEquals( '<div class="test1"></div>', $output );
    }
}
